TRAINING:
  SEED: 1234
  EPOCHS: 40
  BATCH_SIZE: 4
  SHUFFLE: 1000
  EARLY_STOPPING: 3

  LEARNING_RATE:
    INIT: 0.001
    MOMENTUM: 0.9

  IMAGE:
    HEIGHT: 256
    WIDTH: 256

  AUGMENT:
    RESIZE_MAX_SCALE: 1.5
