DATASET:
  NUM_CLASSES: 2

MODEL:
  EXTRA:
    STEM_INPLANES: 64
    FINAL_CONV_KERNEL: 1
    STAGE1:
      NUM_MODULES: 1
      NUM_BRANCHES: 1
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
      NUM_CHANNELS:
        - 32
      FUSE_METHOD: SUM
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
      NUM_CHANNELS:
        - 32
        - 64
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 1
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
        - 4
      NUM_CHANNELS:
        - 32
        - 64
        - 128
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 1
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
        - 4
        - 4
      NUM_CHANNELS:
        - 32
        - 64
        - 128
        - 256
      FUSE_METHOD: SUM
